fragment Work on Work {
  name
  description
  url
  github1
  github2
  thumbnail {
    data {
      attributes {
        url
      }
    }
  }
  display {
    data {
      attributes {
        url
      }
    }
  }
  screenshot {
    data {
      attributes {
        url
      }
    }
  }
}
