query GetWork($id: ID!) {
  work(id: $id) {
    data {
      id
      attributes {
        ...Work
        category {
          data {
            attributes {
              ...Category
            }
          }
        }
      }
    }
  }
}
